2024-07-30 11:56:46,713 INFO    MainThread:14070 [wandb_setup.py:_flush():76] Current SDK version is 0.15.4
2024-07-30 11:56:46,714 INFO    MainThread:14070 [wandb_setup.py:_flush():76] Configure stats pid to 14070
2024-07-30 11:56:46,714 INFO    MainThread:14070 [wandb_setup.py:_flush():76] Loading settings from /Users/mmuhleth/.config/wandb/settings
2024-07-30 11:56:46,714 INFO    MainThread:14070 [wandb_setup.py:_flush():76] Loading settings from /Users/mmuhleth/Desktop/diffusion_graph/wandb/settings
2024-07-30 11:56:46,714 INFO    MainThread:14070 [wandb_setup.py:_flush():76] Loading settings from environment variables: {}
2024-07-30 11:56:46,714 INFO    MainThread:14070 [wandb_setup.py:_flush():76] Applying setup settings: {'_disable_service': False}
2024-07-30 11:56:46,714 INFO    MainThread:14070 [wandb_setup.py:_flush():76] Inferring run settings from compute environment: {'program_relpath': 'train_ppgn_simple.py', 'program': '/Users/mmuhleth/Desktop/diffusion_graph/train_ppgn_simple.py'}
2024-07-30 11:56:46,714 INFO    MainThread:14070 [wandb_init.py:_log_setup():507] Logging user logs to /Users/mmuhleth/Desktop/diffusion_graph/wandb/run-20240730_115646-06oz3j68/logs/debug.log
2024-07-30 11:56:46,714 INFO    MainThread:14070 [wandb_init.py:_log_setup():508] Logging internal logs to /Users/mmuhleth/Desktop/diffusion_graph/wandb/run-20240730_115646-06oz3j68/logs/debug-internal.log
2024-07-30 11:56:46,714 INFO    MainThread:14070 [wandb_init.py:init():547] calling init triggers
2024-07-30 11:56:46,714 INFO    MainThread:14070 [wandb_init.py:init():554] wandb.init called with sweep_config: {}
config: {}
2024-07-30 11:56:46,714 INFO    MainThread:14070 [wandb_init.py:init():596] starting backend
2024-07-30 11:56:46,714 INFO    MainThread:14070 [wandb_init.py:init():600] setting up manager
2024-07-30 11:56:46,718 INFO    MainThread:14070 [backend.py:_multiprocessing_setup():106] multiprocessing start_methods=spawn,fork,forkserver, using: spawn
2024-07-30 11:56:46,723 INFO    MainThread:14070 [wandb_init.py:init():606] backend started and connected
2024-07-30 11:56:46,726 INFO    MainThread:14070 [wandb_init.py:init():703] updated telemetry
2024-07-30 11:56:46,726 INFO    MainThread:14070 [wandb_init.py:init():736] communicating run to backend with 60.0 second timeout
2024-07-30 11:56:46,996 ERROR   MainThread:14070 [wandb_init.py:init():762] encountered error: It appears that you do not have permission to access the requested resource. Please reach out to the project owner to grant you access. If you have the correct permissions, verify that there are no issues with your networking setup.(Error 403: Forbidden)
2024-07-30 11:56:47,054 ERROR   MainThread:14070 [wandb_init.py:init():1170] It appears that you do not have permission to access the requested resource. Please reach out to the project owner to grant you access. If you have the correct permissions, verify that there are no issues with your networking setup.(Error 403: Forbidden)
Traceback (most recent call last):
  File "/opt/anaconda3/envs/digress/lib/python3.9/site-packages/wandb/sdk/wandb_init.py", line 1152, in init
    run = wi.init()
  File "/opt/anaconda3/envs/digress/lib/python3.9/site-packages/wandb/sdk/wandb_init.py", line 768, in init
    raise error
wandb.errors.CommError: It appears that you do not have permission to access the requested resource. Please reach out to the project owner to grant you access. If you have the correct permissions, verify that there are no issues with your networking setup.(Error 403: Forbidden)
2024-07-30 11:56:48,062 WARNING MsgRouterThr:14070 [router.py:message_loop():77] message_loop has been closed
